// dependencies (generated by express)
const createError = require('http-errors');
const express = require('express');
const path = require('path');
const cookieParser = require('cookie-parser');
const logger = require('morgan');

// dependencies
const flash = require('express-flash');
const passport = require('passport');
const initializePassport = require('./config/passport');
initializePassport(passport, user => user);
const methodOverride = require('method-override');
const session = require('express-session');

// router dependencies
const indexRouter = require('./routes/index');
const loginRouter = require('./routes/login');
const registerRouter = require('./routes/register');
const closetRouter = require('./routes/closet');
const addAttireRouter = require('./routes/add-attire');
const editAttireRouter = require('./routes/edit-attire');
const addClosetRouter = require('./routes/add-closet');
const addOutfitRouter = require('./routes/add-outfit');
const removeOutfitRouter = require('./routes/remove-outfit');

const app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'pug');

// allow form data access inside req(uest) variables in POST methods
app.use(express.urlencoded({ extended: false }));

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

//enable session handling
app.use(
  session({
    secret: 'secret',
    resave: true,
    saveUninitialized: true,
  })
);
app.use(passport.initialize());
app.use(passport.session());
app.use(flash());
app.use(methodOverride('_method'));

app.use('/', indexRouter);
app.use('/login', loginRouter);
app.use('/register', registerRouter);
app.use('/closet', closetRouter);
app.use('/add-attire', addAttireRouter);
app.use('/edit-attire', editAttireRouter);
app.use('/add-closet', addClosetRouter);
app.use('/add-outfit', addOutfitRouter);
app.use('/remove-outfit', removeOutfitRouter);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;
